### 분류(Classifier)
- 대표적인 지도학습 방법 중 하나이며, 다양한 문제와 정답을 학습한 뒤 별도의 테스트에서 정답을 예측한다.
- 주어진 문제를 먼저 학습한 뒤 새로운 문제에 대한 정답을 예측하는 방식이다.
- 이진분류(Binary Classification)의 경우 정답은 0(음성, Negative)과 1(양성, Positive)과 같이 True, False값을 가진다.  
<div style="width:500px; height:200px; display: flex; margin-top: 25px; margin-bottom: 25px; margin-left: 0px;">
    <div>
        <img src="./images/classifier01.png" width="200">  
    </div>
    <div style="width: 200px; heigth: 100px; margin-top: 25px; margin-left: 30px;">
        <img src="./images/classifier02.png">  
    </div>
</div>
- 다중 분류(Multiclass Classification)는 정답이 가질 수 있는 값은 3개 이상이다(예: 0, 1, 2).  
<img src="./images/classifier03.png" width="300" style="margin-top: 25px; margin-left: 0px;"> 

###  📌용어 정리
##### 피처(Feature)
- 데이터 세트의 일반 컬럼이며, 2차원 이상의 다차원 데이터까지 통틀어 피처라고 한다.
- 타겟을 제외한 나머지 속성을 의미한다.
##### 레이블(Label), 클래스(Class), 타겟(Target), 결정(Decision)
- 지도 학습 시 데이터의 학습을 위해 주어지는 정답을 의미한다.
- 지도 학습 중, 분류의 경우 이를 레이블 또는 클래스라고도 부른다.

<img src="./images/feature_target.png" width="450" style="margin-left: 0">

### 분류 예측 프로세스
<img src="./images/classifier_flow.png">

### 붓꽃 품종 예측
- 다중 분류(Multiclass Classification)
##### Featuer
- sepal length : 꽃받침의 길이
- sepal width : 꽃받침의 너비
- petal length : 꽃잎의 길이
- petal width: 꽃잎의 너비

##### Target(Label)
- 0 : Setosa
- 1 : Vesicolor
- 2 : Virginica

In [2]:
import sklearn
print(sklearn.__version__)

1.3.0


In [3]:
# 사이킷런 라이브러리에 내장된 iris(붓꽃) 데이터
from sklearn.datasets import load_iris
# 결정 트리 모델
from sklearn.tree import DecisionTreeClassifier
# 학습 데이터 세트와 테스트 데이터 세트를 분리해주는 라이브러리
from sklearn.model_selection import train_test_split

### 붓꽃 데이터 정리
##### 키는 보통 data, target, target_name, feature_names, DESCR로 구성된다.
- data는 feature의 데이터 세트이다.
- target은 레이블 값이다.
- target_names는 각 레이블의 이름이다.
- feature_names는 feature의 이름이다.
- DESCR은 데이터 세트에 대한 설명과 각 feature의 설명이다.

In [14]:
import pandas as pd

# 붓꽃 데이터 세트 불러오기
iris = load_iris()

# 붓꽃 데이터 세트의 key값
# print(f'붓꽃 데이터 세트의 키 {iris.keys()}')

keys = pd.DataFrame(iris.keys()).rename(columns={0: 'key'}).T
# display(keys)

# iris.data는 feature 데이터이며, numpy.ndarray이다.
iris_feature = iris.data
print(iris)
# print(type(iris_feature))
# print(f'iris feature: {iris_feature[:5]}')
# print(f'iris type: {type(iris_feature[:5])}')
# print(f'iris feature name: {iris.feature_names}')

# print("=" * 80)

# iris.target은 붓꽃 데이터 세트에서 타겟(레이블, 결정 값) 데이터를 numpy.ndarray로 가지고 있다.
iris_target = iris.target
# print(f'iris target: {iris_target[:5]}')
# print(f'iris type: {type(iris_target[:5])}')
# print(f'iris target name: {iris.target_names}')

# 붓꽃 데이터 세트 DataFrame으로 변환한다.
# iris_df = pd.DataFrame(data=iris_feature, columns=iris.feature_names)
# iris_df['target'] = iris_target
# display(iris_df.head())
# print(iris_df.info())

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

### 데이터 세트 분리
##### train_test_split(feature, target, test_size, random_state )
- 학습 데이터 세트와 테스트 데이터 세트 분리
- feature: 전체 데이터 세트 중 feature
- target: 전체 데이터 세트 중 target
- test_size: 테스트 세트의 비율(0~1)
- random_state: 매번 동일한 결과를 원할 때, 원하는 Seed값 작성

In [5]:
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(iris_feature, iris_target, test_size=0.2, random_state=124)

print(type(X_train), type(X_test), type(y_train), type(y_test))
print(X_train[:5], X_test[:5], y_train[:5], y_test[:5], sep="\n======================\n")
print(f'전체 데이터 세트 개수: {iris_feature.__len__()}')
print(f'학습 데이터 세트 개수: {X_train.__len__()}')
print(f'타겟 데이터 세트 개수: {X_test.__len__()}')

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[7.9 3.8 6.4 2. ]
 [6.8 3.2 5.9 2.3]
 [6.6 3.  4.4 1.4]
 [5.8 4.  1.2 0.2]
 [4.7 3.2 1.6 0.2]]
[[6.3 3.3 4.7 1.6]
 [5.4 3.9 1.3 0.4]
 [6.3 2.3 4.4 1.3]
 [6.1 2.6 5.6 1.4]
 [6.3 3.4 5.6 2.4]]
[2 2 1 0 0]
[1 0 1 2 2]
전체 데이터 세트 개수: 150
학습 데이터 세트 개수: 120
타겟 데이터 세트 개수: 30


##### train_test_split(feature, target, test_size, random_state)
- DataFrame과 Series도 분할이 가능하다.

In [6]:
import pandas as pd

iris_df = pd.DataFrame(iris_feature, columns=iris.feature_names)
iris_df['target'] = iris_target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [7]:
feature_df = iris_df.iloc[:, :-1]
target_df = iris_df.loc[:, 'target']

display(feature_df.head())
display(target_df.head())

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

In [8]:
X_train, X_test, y_train, y_test = train_test_split(feature_df, target_df, test_size=0.5, random_state=124)

print(X_train[:5], X_test[:5], y_train[:5], y_test[:5], sep="\n")
print(f'전체 데이터 세트 개수: {iris_feature.__len__()}')
print(f'학습 데이터 세트 개수: {X_train.__len__()}')
print(f'타겟 데이터 세트 개수: {X_test.__len__()}')

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                  4.4               2.9                1.4               0.2
149                5.9               3.0                5.1               1.8
15                 5.7               4.4                1.5               0.4
18                 5.7               3.8                1.7               0.3
33                 5.5               4.2                1.4               0.2
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
56                 6.3               3.3                4.7               1.6
16                 5.4               3.9                1.3               0.4
87                 6.3               2.3                4.4               1.3
134                6.1               2.6                5.6               1.4
136                6.3               3.4                5.6               2.4
8      0
149    2
15     0
18     0
33     0
Name: target, dtype

### 모델 학습
##### fit(train_feature, train_target)
- 모델을 학습시킬 때 사용한다.
- train_feature: 학습 데이터 세트 중 feature
- train_target: 훈련 데이터 세트 중 target

In [9]:
# DecisionTreeClassifier 객체 생성
decision_tree_classifier = DecisionTreeClassifier()

# 모델 학습 수행
decision_tree_classifier.fit(X_train, y_train)

DecisionTreeClassifier()

### 예측 수행
##### predict(test_feature)
- 학습된 모델에 테스트 데이터 세트의 feature를 전달하여 target을 예측한다.
- test_feature: 테스트 데이터 세트 중 feature

In [10]:
prediction = decision_tree_classfier.predict(X_test)
print(prediction)

NameError: name 'decision_tree_classfier' is not defined

### 정확도
##### accuracy_score(test_target, prediction)
- 모델의 예측 정확도(Accuracy)를 사용하여 예측률을 구하여 평가할 수 있다.

In [ ]:
from sklearn.metrics import accuracy_score
print(f"예측 정확도: {accuracy_score(y_test, prediction)}")